[package]
name = "rembrandt"
version = "0.4.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "rembrandt"
path = "src/lib.rs"

[[bin]]
name = "bench-kernels"
path = "tools/bench-kernels.rs"

[[bin]]
name = "bench-cudnn"
path = "tools/bench-cudnn.rs"

[[bin]]
name = "run-rembrandt"
path = "tools/run-rembrandt.rs"

[dependencies]
byteorder = "*"
rand = "*"
time = "*"

[dependencies.array]
path = "../libarray"

[dependencies.async]
path = "../libasync"

[dependencies.async_cuda]
path = "../libasync_cuda"

[dependencies.cuda_dnn]
path = "../libcuda_dnn"

[dependencies.linalg]
path = "../liblinalg"

[dependencies.lmdb]
path = "../liblmdb"

[dependencies.protobuf]
path = "../rust-protobuf"

[dependencies.rembrandt_kernels]
path = "../rembrandt_kernels"

[dependencies.toml]
path = "../third_party/toml-rs"
